#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: mandyrose

"""

class Calculator():
    
    def add(self, x, y):
        number_types = (int, float, complex)
        try:
            if isinstance(x, number_types) and isinstance(y, number_types):
                return x + y
        except ValueError:
            return ValueError

    def multiply(self, x, y):
        number_types = (int, float, complex)
        try:
            if isinstance(x, number_types) and isinstance(y, number_types):
                return x * y
        except ValueError:
            return ValueError
    def subtract(self, x, y):
        number_types = (int, float, complex)
        try:
            if isinstance(x, number_types) and isinstance(y, number_types):
                return x - y
        except ValueError:
            return ValueError

